### ISSUE TITLE
issue with installations

### ISSUE THREAD

**Issue by JanekKondzior** [fedy/fedy#634] opened 2018-11-16 01:18 UTC
sudo dnf install https://dl.folkswithhats.org/fedora/$(rpm -E %fedora)/RPMS/fedy-release.rpm
Last metadata expiration check: 0:00:50 ago on Fri 16 Nov 2018 12:14:18 PM EST.
[MIRROR] fedy-release.rpm: Status code: 403 for https://dl.folkswithhats.org/fedora/29/RPMS/fedy-release.rpm
[FAILED] fedy-release.rpm: Status code: 403 for https://dl.folkswithhats.org/fedora/29/RPMS/fedy-release.rpm
Status code: 403 for https://dl.folkswithhats.org/fedora/29/RPMS/fedy-release.rpm

**Comment by berkcodes** [comment] 2018-11-16 04:02
Hi Janek, 

Unfortunately Fedy for F29 hasn't been made available as a RPM package yet. If you still would like to use Fedy, you can install it manually by following the steps here: https://github.com/fedy/fedy/issues/632#issuecomment-438663429

Duplicate of #632

**Comment by danstewart** [comment] 2018-11-16 10:53
Closed as duplicate of #632 


Here are the instructions to install from source
```
# Clone and install
git clone https://github.com/fedy/fedy.git && cd fedy && sudo make install

# Clean up
cd .. && rm -r fedy`
```

**Closed by danstewart** 2018-11-16 10:53 UTC

**Comment by JanekKondzior** [comment] 2018-11-19 12:01
ah okay,  thanks guys. i'm quite new too fedora!

**Comment by emanueltobias** [comment] 2018-11-28 02:50
Thanks, 
to delete the directory use
# Clean up
cd .. && rm -r fedy

**Comment by souhaiebtar** [comment] 2019-04-28 09:45
what i did, to make it work,
```
sudo dnf install gjs
```
than like said above

```
git clone https://github.com/fedy/fedy.git && cd fedy && sudo make install

cd .. && rm -r fedy

```
after launching,
now the application launch correctly but there still a problem with some icon,

to resolve that i installed papirus-icon-theme and switched to it
to install papirus-icon-theme, i used

```bash
sudo dnf copr enable dirkdavidis/papirus-icon-theme

sudo dnf install papirus-icon-theme
```
